# Generated by Django 4.0.4 on 2022-05-11 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Podium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_limit', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('valid_from', models.IntegerField()),
                ('valid_to', models.IntegerField()),
                ('username', models.CharField(max_length=128)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesite.festival')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesite.festival')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=128)),
                ('arrives', models.DateTimeField(default=datetime.datetime.now)),
                ('performance_time', models.DateTimeField(default=datetime.datetime.now)),
                ('festival_iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesite.festival')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesite.genre')),
                ('podium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesite.podium')),
            ],
        ),
    ]
